spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    generate-ddl: true
  jmx:
    enabled: false
  mail:
    properties.mail.smtp:
      connecttimeout: 5000
      timeout: 3000
      writetimeout: 5000
#    test-connection: true
    host: smtp.gmail.com
    port: 587
    username: com.ilya.ivanov@gmail.com
    password: Ivanov123
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
#      mail.mime.multipart.allowempty: true
  hibernate:
    max_fetch_depth: 3
    jdbc:
      fetch_size: 50
      batch_size: 10
logging:
  file: logs/devman.log
by.itransition:
      service:
        user:
          credential:
            alwaysGenerateOnRegistration: false
            defaultPasswordGeneratorName: by.itransition.service.user.impl.RandomPasswordGenerator
          defaultAuthority: ROLE_USER
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
    database: H2
  datasource:
    url: jdbc:h2:mem:notes_db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
logging:
  level:
    org.hibernate: info
    javafx.*: info
    org.springframework: info
    org.jboss.logging: info
    org.apache.commons: info
    .: debug
---
spring:
  profiles: prod
  jpa:
      hibernate:
        ddl-auto: create
      database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/devman
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
logging:
  level:
    org.hibernate: warn
    javafx.*: warn
    org.springframework: warn
    org.jboss.logging: warn
    org.apache.commons: warn
    .: info