package by.itransition.service.user;

import org.springframework.security.core.GrantedAuthority;

/**
 * Created by ilya on 6/18/17.
 */
public interface SecurityPolicy {
    /**
     * Policy item determine whether password must be force generated by system
     * on each user registration or not.
     * @return
     */
    boolean alwaysGenerateOnRegistration();

    /**
     * Policy item determine default strategy of password generator.
     * @return
     */
    Class<PasswordGenerator> defaultPasswordGeneratorType();

    GrantedAuthority getDefaultRegistrationAuthority();
}
